<a href="https://colab.research.google.com/github/cwanko/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns

y_df = attrition_df[['Attrition', 'Department']]

# Display the first few rows of the new DataFrame
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:


# Create a list of at least 10 column names to use as X data
selected_columns = ['Age', 'BusinessTravel', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction',
                    'JobInvolvement', 'JobSatisfaction', 'NumCompaniesWorked', 'WorkLifeBalance',
                    'TotalWorkingYears']

# Create X_df using the selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
X_df.dtypes



Age                         int64
BusinessTravel             object
DistanceFromHome            int64
Education                   int64
EnvironmentSatisfaction     int64
JobInvolvement              int64
JobSatisfaction             int64
NumCompaniesWorked          int64
WorkLifeBalance             int64
TotalWorkingYears           int64
dtype: object

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)


In [7]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# Convert the 'BusinessTravel' column in X_df to numeric using one-hot encoding
X_df_numeric = pd.get_dummies(X_df, columns=['BusinessTravel'], drop_first=True)

# Check the data types after conversion
X_df_numeric.dtypes


Age                                 int64
DistanceFromHome                    int64
Education                           int64
EnvironmentSatisfaction             int64
JobInvolvement                      int64
JobSatisfaction                     int64
NumCompaniesWorked                  int64
WorkLifeBalance                     int64
TotalWorkingYears                   int64
BusinessTravel_Travel_Frequently     bool
BusinessTravel_Travel_Rarely         bool
dtype: object

In [9]:


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df_numeric, y_df, test_size=0.2, random_state=42)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Display the first 5 rows of scaled data
X_train_scaled[:5], X_test_scaled[:5]


(array([[-1.38855944,  1.44039645, -0.86335572,  0.2797056 , -1.01234042,
         -1.58233648, -1.05916816,  0.3574354 , -1.1673683 , -0.49041445,
          0.63904869],
        [-2.04073779, -0.52269928, -0.86335572, -0.63910385,  0.38991203,
          1.15283407, -0.65943075,  0.3574354 , -1.42339685, -0.49041445,
         -1.56482598],
        [-0.84507748,  1.31770296, -0.86335572,  1.19851504,  0.38991203,
          1.15283407, -0.25969335,  0.3574354 , -0.14325407, -0.49041445,
          0.63904869],
        [ 0.24188644,  0.3361551 ,  0.09993302,  1.19851504,  0.38991203,
         -0.67061296,  0.53978146,  0.3574354 , -0.52729691, -0.49041445,
          0.63904869],
        [-0.62768469,  1.31770296,  0.09993302, -0.63910385,  0.38991203,
          0.24111056, -0.65943075,  0.3574354 , -0.14325407, -0.49041445,
          0.63904869]]),
 array([[-0.95377387, -0.52269928,  0.09993302,  1.19851504,  0.38991203,
         -1.58233648, -1.05916816,  0.3574354 , -0.65531119, -0.49041

In [16]:


from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder instance for the Department column
encoder = OneHotEncoder(sparse_output=False, drop='first')

# Fit the encoder to the Department column in the training data
encoder.fit(y_train[['Department']])

# Apply the encoder to the training and testing data
department_train_encoded = encoder.transform(y_train[['Department']])
department_test_encoded = encoder.transform(y_test[['Department']])

# Display the first few rows of the encoded department data
department_train_encoded[:5], department_test_encoded[:5]





(array([[1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.]]),
 array([[0., 1.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.]]))

In [19]:


from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder instance for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the Attrition column in the training data
attrition_encoder.fit(y_train[['Attrition']])

# Apply the encoder to the training and testing data
attrition_train_encoded = attrition_encoder.transform(y_train[['Attrition']])
attrition_test_encoded = attrition_encoder.transform(y_test[['Attrition']])

# Display the first few rows of the encoded attrition data
print(attrition_train_encoded[:5])


[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [26]:


import tensorflow as tf
from tensorflow.keras import layers


# Find the number of columns in the X training data
input_dim = X_train_scaled.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(input_dim,), name='input')

# Create shared layers
shared_layer_1 = layers.Dense(64, activation='relu', name='shared1')(input_layer)
shared_layer_2 = layers.Dense(128, activation='relu', name='shared2')(shared_layer_1)

# Output the input and shared layers
input_layer, shared_layer_1, shared_layer_2




(<KerasTensor shape=(None, 11), dtype=float32, sparse=None, name=input>,
 <KerasTensor shape=(None, 64), dtype=float32, sparse=False, name=keras_tensor_11>,
 <KerasTensor shape=(None, 128), dtype=float32, sparse=False, name=keras_tensor_12>)

In [27]:

# Create the hidden layer for the Department branch
department_hidden_layer = layers.Dense(32, activation='relu', name='department_hidden')(shared_layer_2)

# Create the output layer for the Department branch
department_output_layer = layers.Dense(3, activation='softmax', name='department_output')(department_hidden_layer)

# Display the Department branch layers
department_hidden_layer, department_output_layer



(<KerasTensor shape=(None, 32), dtype=float32, sparse=False, name=keras_tensor_13>,
 <KerasTensor shape=(None, 3), dtype=float32, sparse=False, name=keras_tensor_14>)

In [28]:

# Create the hidden layer for the Attrition branch
attrition_hidden_layer = layers.Dense(32, activation='relu', name='attrition_hidden')(shared_layer_2)

# Create the output layer for the Attrition branch
attrition_output_layer = layers.Dense(2, activation='softmax', name='attrition_output')(attrition_hidden_layer)

# Display the Attrition branch layers
attrition_hidden_layer, attrition_output_layer



(<KerasTensor shape=(None, 32), dtype=float32, sparse=False, name=keras_tensor_15>,
 <KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_16>)

In [31]:

# Create the model with inputs and two output branches
model = Model(inputs=input_layer, outputs=[attrition_output_layer, department_output_layer])

# Compile the model
model.compile(optimizer='adam',
              loss={'attrition_output': 'categorical_crossentropy',
                    'department_output': 'categorical_crossentropy'},
              metrics=['accuracy'])

# Summarize the model
model.summary()


Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)        │ (None, 11)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared1 (Dense)           │ (None, 64)             │            768 │ input[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared2 (Dense)           │ (None, 128)            │          8,320 │ shared1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden (Dense)  │ (None, 32)             │          4,128 │ shared2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden (Dense) │ (None, 32)             │          4,128 │ shared2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             66 │ attrition_hidden[0][0] │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             99 │ department_hidden[0][… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 17,509 (68.39 KB)

 Trainable params: 17,509 (68.39 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:

# Encode Attrition (binary classification)
attrition_encoder = OneHotEncoder(sparse_output=False)
attrition_train_encoded = attrition_encoder.fit_transform(y_train[['Attrition']])
attrition_test_encoded = attrition_encoder.transform(y_test[['Attrition']])

# Encode Department (multi-class classification)
department_encoder = OneHotEncoder(sparse_output=False)
department_train_encoded = department_encoder.fit_transform(y_train[['Department']])
department_test_encoded = department_encoder.transform(y_test[['Department']])

# Compile the model with metrics for both outputs
model.compile(optimizer='adam',
              loss={'attrition_output': 'categorical_crossentropy',
                    'department_output': 'categorical_crossentropy'},
              metrics={'attrition_output': 'accuracy',
                       'department_output': 'accuracy'})

# Train the model
history = model.fit(
    X_train_scaled,
    {'attrition_output': attrition_train_encoded, 'department_output': department_train_encoded},
    epochs=20,
    batch_size=32,
    validation_split=0.2
)



Epoch 1/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - attrition_output_accuracy: 0.8436 - department_output_accuracy: 0.4274 - loss: 1.5187 - val_attrition_output_accuracy: 0.7966 - val_department_output_accuracy: 0.6314 - val_loss: 1.3321
Epoch 2/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8512 - department_output_accuracy: 0.6449 - loss: 1.2109 - val_attrition_output_accuracy: 0.7966 - val_department_output_accuracy: 0.6314 - val_loss: 1.2896
Epoch 3/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8512 - department_output_accuracy: 0.6230 - loss: 1.1848 - val_attrition_output_accuracy: 0.7966 - val_department_output_accuracy: 0.6314 - val_loss: 1.2881
Epoch 4/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8389 - department_output_accuracy: 0.6548 - loss: 1.1447 - val_attrition_output_accuracy: 0.8008 - val_department_output_accuracy: 0.6314 - val_loss: 1.2909
Epoch 5/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/st

In [51]:

# Evaluate the model using the testing data
evaluation = model.evaluate(
    X_test_scaled,
    {'attrition_output': attrition_test_encoded, 'department_output': department_test_encoded}
)

# Print the accuracies from the evaluation results
print(f"Attrition accuracy: {evaluation[1]}")
print(f"Department accuracy: {evaluation[2]}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8537 - department_output_accuracy: 0.5699 - loss: 1.4338 
Attrition accuracy: 0.8673469424247742
Department accuracy: 0.6088435649871826


In [52]:
# Compile the model with separate loss and metrics for each output
model.compile(optimizer='adam',
              loss={'attrition_output': 'categorical_crossentropy',
                    'department_output': 'categorical_crossentropy'},
              metrics={'attrition_output': 'accuracy',
                       'department_output': 'accuracy'})

In [53]:
# Evaluate the model using the testing data
evaluation = model.evaluate(
    X_test_scaled,
    {'attrition_output': attrition_test_encoded, 'department_output': department_test_encoded}
)

# Print the accuracies for both outputs
print(f"Attrition accuracy: {evaluation[1]}")
print(f"Department accuracy: {evaluation[2]}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - attrition_output_accuracy: 0.8537 - department_output_accuracy: 0.5699 - loss: 1.4338  
Attrition accuracy: 0.8673469424247742
Department accuracy: 0.6088435649871826


In [54]:
# Evaluate the model using the testing data
evaluation = model.evaluate(
    X_test_scaled,
    {'attrition_output': attrition_test_encoded, 'department_output': department_test_encoded}
)

# Print the accuracies for both outputs
print(f"Attrition accuracy: {evaluation[1]}")
print(f"Department accuracy: {evaluation[2]}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8537 - department_output_accuracy: 0.5699 - loss: 1.4338 
Attrition accuracy: 0.8673469424247742
Department accuracy: 0.6088435649871826


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy is not always the best especially if the data are inbalanced. The accuracy will be misleading by representing the majority class.

2. I used the softmax for my output layers. The attrition output is binary "yes" or "no".For the department output layer, softmax ensuresensures the sum of predicted probabilities across all classes is 1.

3. Handling Class Imbalance: we could use the SMOTE (Synthetic Minority Over-sampling Technique), undersampling, or class weights during training could improve performance. We could also use deep learning models like CNN.